function dist = dijkstra_sparse(W, source)
% NOTE: fully generated by ChatGPT

N = size(W,1);
dist = inf(1,N);
visited = false(1,N);

dist(source) = 0;

for i = 1:N
    % pick unvisited node with smallest distance
    [~, u] = min(dist + visited*max(dist)*2);
    visited(u) = true;

    neighbors = find(W(u,:) > 0);

    for v = neighbors
        alt = dist(u) + W(u,v);
        if alt < dist(v)
            dist(v) = alt;
        end
    end
end
end