function [Y, D_geo] = isomap(X, k)
% NOTE: fully generated by ChatGPT
% X: Nx3 point cloud
% k: number of nearest neighbors
% Y: Nx2 embedding (s,q)
% D_geo: geodesic distance matrix

N = size(X,1);

%% Step 1: k-NN graph
[idx, dist] = knnsearch(X, X, 'K', k+1); % includes self
idx = idx(:,2:end);
dist = dist(:,2:end);

% Build sparse adjacency matrix
I = repmat((1:N)',1,k);
W = sparse(I(:), idx(:), dist(:), N, N);

% Make symmetric (important!)
W = min(W, W');

G = graph(W);
% bins = conncomp(G);
% num_components = max(bins);
% 
% fprintf('Connected components: %d\n', num_components);

%% Step 2: Geodesic distances (Dijkstra)
% D_geo = inf(N,N);

% for i = 1:N
%     D_geo(i,:) = dijkstra_sparse(W, i);
% end
D_geo = distances(G);

%% Step 3: Classical MDS (Isomap)
% Centering matrix
H = eye(N) - ones(N)/N;

% Double centering
K = -0.5 * H * (D_geo.^2) * H;

% Eigen-decomposition
[Vec, Val] = eigs(K, 2);

% Coordinates
Y = Vec * sqrt(Val);

end